---
logger:
  project_name: 'seals5454/3sdu'
  exp_name: dgcnn_byol_classic
  tags: ['point_cloud', 'byol', 'patches']
  api_token:
    "eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmU\
    uYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS\
    5haSIsImFwaV9rZXkiOiI2NTIwODVkNC1hOTg5LTQ4NTAtY\
    WRhNS0yMGY4MmQ1YzBmZWIifQ=="

data:
  name: shapenet_part
  path: '../datasets/hdfs/shapenet_10patches_10rots.h5'
  modalities: ['point_cloud']
  batch_size: 7
  aug: [True, [xyz, -45, 45], True, False]

model:
  flatten_embeddings: True
  mlp: False
  reduction: mean
  n_output: 512
  proj_dim: 128
  hidden_size: 2048

train:
  framework: byol
  total_epochs: 200
  lr: 1.e-3
  weight_decay: 1.e-5
  tau: 0.07
  save_every: 100
  weights_root: './weights'
  moving_average_decay: 0.9995
